### ISSUE TITLE
what's wrong with my code?

### ISSUE THREAD

**Issue by HUI2125281** [wil93/mailipy#9]
I download the source ,then install required package, when run gen script

`C:\Users\ju\IdeaProjects\mailipy>mailipy\gen.py sample_template.md sample_contacts.csv
Traceback (most recent call last):
  File "C:\Users\jui\IdeaProjects\mailipy\mailipy\gen.py", line 213, in <module>
    main()
  File "C:\Users\ju\IdeaProjects\mailipy\mailipy\gen.py", line 133, in main
    env.globals.update(__builtins__)
TypeError: 'module' object is not iterable`

**Comment by HUI2125281** [comment]
'pip install mailipy'
is work ,bug the source code in system directory.
how to run under my project directory?

**Comment by wil93** [comment]
To run mailipy from the source, you need to run `pipenv install` followed by `pipenv shell`.

I will add now some more instructions to the README file.

**Comment by HUI2125281** [comment]
thanks a lot
